Validate rspectest
katfogy/blog-app pull request #3
Opened 2023-08-18 08:01 UTC by katfogy

**In this milestone,**
- [ ]     I created validations for the models.
- [ ]     I created tests for the models.

2023-08-18 09:25 UTC, jerryowusu requested changes
Hi @katfogy  

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![noooo](https://github.com/katfogy/blog-app/assets/65233860/3c66878f-39d4-4f5b-a4ce-fa096e43fe2a)


## Highlights
Neat and well organized code :+1: 
Validation tests passing :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 09:25 UTC, jerryowusu commented on spec/models/like_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom method in the models should have a corresponding unit test. Kindly consider to add a unit test for the `update_like_count` method in the like model here. :pray:

2023-08-18 09:25 UTC, jerryowusu commented on spec/models/comment_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom method in the models should have a corresponding unit test. Kindly consider to add a unit test for the `update_comment_count` method in the comment model here. :pray:

2023-08-18 09:25 UTC, jerryowusu commented on spec/models/post_spec.rb
> +  end
Nice job so far. However, as part of the project requirements, any custom method in the models should have a corresponding unit test. Kindly consider to add a unit test for the `update_posts_count` and `five_most_recent_comments` methods in the post model here. :pray:

2023-08-18 11:52 UTC, VICTOR-CHUKWU approved these changes
Hi @katfogy , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] all test passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 11:53 UTC, merged

2023-09-23 10:26 UTC, NahnahAJ commented
## Project Status: APPROVED :green_circle: 
Hi @katfogy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/3Hb1STCbFroaErsYT0/giphy.gif"/>

## Highlights :fire: 
- All project requirements met :heavy_check_mark: 
- Project previously approved :heavy_check_mark: 
- All linter checks passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 07:03 UTC, binhussen reviewed
Hi @katfogy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Added Controller Specs ✔️
- Well Structured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._